name: Install Methods
on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
jobs:
  install_script:
    name: Install Script
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml:docker-compose.volumes.yml
      DEVSHOP_DOCKER_IMAGE: devshop/base

    steps:
    - uses: actions/checkout@v2
    - name: Run Install Script
      run: bash .github/workflows/install.sh
