name: Install Methods
on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
jobs:
  install_script:
    name: Install Script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch a base container
      run: docker-compose up -d
      env:
        - COMPOSE_FILE: docker-compose.yml:docker-compose.volumes.yml
        - DEVSHOP_DOCKER_IMAGE: devshop/base

    - name: System Status
      run: |
        sleep 5
        systemctl status

    - name: install.sh
      run: bash install/install.sh
