name: Install Methods
on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
jobs:
  install_script:
    name: Install Script
    runs-on: ubuntu-latest
    container:
      image: devshop/base:ubuntu1804
      options: --hostname=devshop.local.computer --entrypoint=$PWD/docker/bin/docker-systemd-entrypoint --publish=80:80
      volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

    steps:
    - uses: actions/checkout@v2
    - name: Operating System
      run: uname -a
    - name: Environment
      run: env
    - name: System Status
      run: /github/workspace/scripts/wait-for systemctl status
    - name: install.sh
      run: bash install/install.sh
