name: Install Methods
on:
  push:
    branches: 1.x
  pull_request:
    types: [opened, synchronize]
jobs:
  install_script:
    runs-on: ubuntu-latest
    container:
      image: devshop/base:ubuntu1804
      options: "--entrypoint=/github/workspace/docker/bin/docker-systemd-entrypoint"
      volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

    steps:
    - uses: actions/checkout@v2
    - name: Operating System
      run: uname -a
    - name: Environment
      run: env
